### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/positive_examples'

### ISSUE THREAD

**Issue by visze** [kircherlab/negative_training_sampler#5]
`negative_training_sampler -o examples examples/input.bed.gz <fasta_file>`

```
/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/fsspec/implementations/local.py:33: FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
  FutureWarning,
Traceback (most recent call last):
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/bin/negative_training_sampler", line 8, in <module>
    sys.exit(main())
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/negative_training_sampler/__main__.py", line 11, in main
    sys.exit(cli.cli())
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/negative_training_sampler/cli.py", line 34, in cli
    memory_per_core=memory)
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/negative_training_sampler/negative_training_balancer.py", line 64, in balance_trainingdata
    save_to_file(negative_sample_cleaned, positive_sample_cleaned, output_file)
  File "/fast/users/schubacm_c/work/miniconda3/envs/MPRADesign/lib/python3.6/site-packages/negative_training_sampler/save_to_file.py", line 18, in save_to_file
    with open(out_path.format("/positive_"), "w") as file:
PermissionError: [Errno 13] Permission denied: '/positive_examples'
```

**Comment by visze** [comment]
without `-o` I get the error message 

`PermissionError: [Errno 13] Permission denied: '/positive_samples.tsv'`

**Comment by visze** [comment]
with ` -o ./examples/` it works

**Comment by visze** [comment]
I think I found out what causes the troubles with the empty negative file (but nit the wrong naming). I use a bed file as input with multiple columns beside chr, start, end and name (used as label).

my input file looks like this:
```
zcat examples/chr8.possibleInput_w300_s50_openChromatin.HepG2.bed.gz | head -n 10
chr8    0       300     0       .       +
chr8    50      350     0       .       +
chr8    100     400     0       .       +
chr8    150     450     0       .       +
chr8    200     500     0       .       +
chr8    250     550     0       .       +
chr8    300     600     0       .       +
chr8    350     650     0       .       +
chr8    400     700     0       .       +
chr8    450     750     0       .       +
```

The positive label (1) has a score in float format at the score column of BED.

The positive output is:
```
cat examples/positive_ | head -n 10CHR     START   END     label_1 label_2 label_3 gc
chr8    83498   83798   1       1.000000        +       57.666702
chr8    206521  206821  1       0.973333        +       65.0
chr8    206889  207189  1       0.966667        +       64.333305
chr8    213289  213589  1       0.900000        +       50.666702
chr8    214552  214852  1       0.946667        +       40.6667
chr8    229534  229834  1       0.983333        +       64.0
chr8    232229  232529  1       1.000000        +       70.6667
chr8    232604  232904  1       1.000000        +       66.6667
chr8    232879  233179  1       0.930000        +       56.0
```
negative empty.

I change the output to two columns: 
```
chr8	0	300	0
chr8	50	350	0
chr8	100	400	0
chr8	150	450	0
chr8	200	500	0
chr8	250	550	0
chr8	300	600	0
chr8	350	650	0
chr8	400	700	0
chr8	450	750	0
```

the output is:
```
cat examples/test/positive_ | head -n 10
CHR	START	END	label_1	gc
chr8	83498	83798	1.0	57.666702
chr8	206521	206821	1.0	65.0
chr8	206889	207189	1.0	64.333305
chr8	213289	213589	1.0	50.666702
chr8	214552	214852	1.0	40.6667
chr8	229534	229834	1.0	64.0
chr8	232229	232529	1.0	70.6667
chr8	232604	232904	1.0	66.6667
chr8	232879	233179	1.0	56.0
cat examples/test/negative_ | head -n 10
CHR	START	END	label_1	gc
chr8	74800	75100	0.0	42.0
chr8	78500	78800	0.0	50.333298
chr8	81800	82100	0.0	42.666702
chr8	85500	85800	0.0	41.3333
chr8	89250	89550	0.0	56.666702
chr8	91950	92250	0.0	61.6667
chr8	94850	95150	0.0	67.666695
chr8	94900	95200	0.0	68.0
chr8	99400	99700	0.0	49.6667
```

My suggestion is: Please support fully the BED format. And you can use the name collumn as label. Then you have to support also strings and not only integers/floats.

The output is again in the wrong files.
